server:
  port: 0

spring:
  application:
    name: auth-service
  profiles:
    active: db, jwt

  # MySQL
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}


  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # discovery-server

# JWT
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}