server:
  port: 10000
#  port: 8080

spring:
  application:
    name: user-service
  profiles:
    active: db


  # MySQL
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

# Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: user-service
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.129.32:8761/eureka # discovery-server
