cloud:
  aws:
    s3:
      bucket: tt.image
    credentials:
      access-key: AKIAYWTZSIEKWO3QOSJU
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todaytrend
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

