server:
  port: 8000

spring:
  application:
    name: apigateway-server
  profiles:
    active: jwt

  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
              - PUT
              - PATCH
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/users/**

      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/api/auth/**

      - id: post-service
        uri: lb://POST-SERVICE
        predicates:
          - Path=/api/post/**

      - id: image-service
        uri: lb://IMAGE-SERVICE
        predicates:
          - Path=/api/image/**

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # discovery-server

# JWT
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}