server:
  port: 8000

spring:
  application:
    name: apigateway-server
  profiles:
    active: jwt

  cloud:
    gateway:
      default-filters:
        - name: LogFilter
#        - name: CustomTokenExpirationFilter
      routes:
      - id: user-service
#        uri: lb://USER-SERVICE
        uri: http://3.38.107.1.10000/
        predicates:
          - Path=/api/users/**

      - id: auth-service
#        uri: lb://AUTH-SERVICE
        # 해당 인스턴스 퍼블릭 IP
        uri: http://3.39.189.167:9000/
        predicates:
          - Path=/api/auth/**

      - id: post-service
#        uri: lb://POST-SERVICE
        uri: http://13.125.79.9/11000/
        predicates:
          - Path=/api/post/**

      - id: image-service
#        uri: lb://IMAGE-SERVICE
        uri: http://3.38.93.126/12000/
        predicates:
          - Path=/api/images/**

# Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: apigateway-server
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.129.32:8761/eureka # discovery-server

# JWT
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}

logging:
  level:
    org:
      springframework:
        security=DEBUG: